### ISSUE TITLE
Tests not working after installation like in the description

### ISSUE THREAD

**Issue by Imdrail** [automl/RoBO#3]
The first 3 tests out of the package robo.test are not working for me after installing robo. I reinstalled it several times now and i always get the same error message, which i will post under my text. test_test_functions is working, but test_ei, test_logei and test_pi are not. Each of them throws an error about needing at least some parameters and and that it has given exactly that much. These errors occur after a fresh installation. Also note that i discarded most of the path for better reading, but the path usually is much much longer and correct.

ERROR: test (__main__.EITestCase1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/robo/test/test_ei.py", line 31, in test
    ei_par_0 = EI(self.model, X_upper=X_upper, X_lower=X_lower,  par=0.0, derivative=True)
TypeError: __init__() takes at least 5 arguments (5 given)

======================================================================
ERROR: test (__main__.LogEITestCase1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/robo/test/test_logei.py", line 30, in test
    log_ei_par_0 = LogEI(self.model, X_upper=X_upper, X_lower=X_lower,  par=0.0, derivative=True)
TypeError: __init__() takes at least 5 arguments (5 given)

======================================================================
ERROR: test (__main__.PITestCase1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/robo/test/test_pi.py", line 38, in test
    out0 = np.array([ pi_par_0(np.array([[x]]), derivative=True) for x in x_values])
TypeError: __call__() takes at least 3 arguments (3 given)

**Comment by aaronkl** [comment]
Hey, unfortunately  we haven't updated the unit test after we refactored RoBO. I fixed them now such that they should run through now. There are still somewhat rudimentary but we will extend them in the near future
