### ISSUE TITLE
logger level not consistently used

### ISSUE THREAD

**Issue by sfalkner** [automl/RoBO#58]
Setting the logger level to ERROR via

import logging
logging.basicConfig(level=logging.ERROR)

in the main script and running fmin.bayesian_optimization still shows some INFO level messages like:

INFO - robo.solver.bayesian_optimization - Evaluate: [ 0.01911752  0.26346699]
INFO - robo.solver.bayesian_optimization - Configuration achieved a performance of 0.126988 in 0.000073 seconds
INFO - robo.solver.bayesian_optimization - Evaluate: [ 0.14746159  0.24377217]
INFO - robo.solver.bayesian_optimization - Configuration achieved a performance of 0.133385 in 0.000067 seconds
INFO - robo.solver.bayesian_optimization - Evaluate: [ 0.80638426  0.75182616]
INFO - robo.solver.bayesian_optimization - Configuration achieved a performance of 0.199793 in 0.000087 seconds
INFO - robo.solver.bayesian_optimization - Start iteration 3 ... 
INFO - robo.solver.bayesian_optimization - Train model...
INFO - robo.solver.bayesian_optimization - Time to train the model: 1.165002
INFO - robo.solver.bayesian_optimization - Maximize acquisition function...
INFO - robo.solver.bayesian_optimization - Time to maximize the acquisition function: 1.187946
INFO - robo.solver.bayesian_optimization - Optimization overhead was 2.366953 seconds
INFO - robo.solver.bayesian_optimization - Next candidate

**Comment by aaronkl** [comment]
fixed
