### ISSUE TITLE
Installation instructions don't mention repo or download url

### ISSUE THREAD

**Issue by amueller** [automl/RoBO#67]
It's kinda hard to get from the docs to the github repo. The only link is in the "contact" section. Maybe consider adding it to the menu.
Also, the installation docs don't mention where to get it from at all: http://automl.github.io/RoBO/installation.html

Btw, it might be good to say why you need a for-loop to iterate over the requirements instead of doing the standard one-liner.

**Comment by numairmansur** [comment]
Hi,
Thanks for pointing it out. We have made the changes in the installation page:
![image](https://user-images.githubusercontent.com/4897599/28932087-91eeae42-7878-11e7-8f3b-0101d647ec73.png)

We used a for-loop because we wanted to preserve the order of installation in the requirements file.

**Comment by amueller** [comment]
That's what I figured ;) Maybe mention that?

**Comment by amueller** [comment]
I'd still maybe add a link to the repo page somewhere, like the "fork me on github" ribbon or an entry to the menu.

**Comment by numairmansur** [comment]
Done. Thanks :)

**Comment by amueller** [comment]
Thank you :)
