### ISSUE TITLE
ImportError: No module named setuptools

### ISSUE THREAD

**Issue by qqTYXn7** [automl/RoBO#71]
I followed the manual installation instructions but was given an error on the final step.

RoBO $ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools

**Comment by aaronkl** [comment]
Could you try to install setuptools via:
pip install setuptools

**Comment by qqTYXn7** [comment]
That worked, thanks.
Now it's giving the error: RuntimeError: Required library HODLR not found. Check the documentation for solutions.

**Comment by aaronkl** [comment]
The problem is due to george, the GP library we use inside RoBO. 
How did you install the requirements of RoBO? Did you execute 

for req in $(cat all_requirements.txt); do pip install $req; done


Could you also make sure that you installed all the requirements of george http://dan.iel.fm/george/current/user/quickstart/#installation

**Comment by qqTYXn7** [comment]
Didn't work.
While installing the requirements and george I got errors like:

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-RFWuet/george/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-9DEWsG-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-RFWuet/george/

**Comment by qqTYXn7** [comment]
Managed to get george installed by installing the packages python-all and python-all-dev.
Installing reqs seems to not have less issues now.

Tried installing RoBo and got the following:

`Installed /usr/local/lib/python2.7/dist-packages/RoBO-0.2.1-py2.7.egg
Processing dependencies for RoBO==0.2.1
Searching for DIRECT
Reading https://pypi.python.org/simple/DIRECT/
Downloading https://pypi.python.org/packages/2e/31/04e3847b1bf6c0a21f21aecbbe6c242ef1ed9ac7711ae6ce859cb985f738/DIRECT-1.0.1.tar.gz#md5=943d257700a9a8c7297fbca50ef09d38
Best match: DIRECT 1.0.1
Processing DIRECT-1.0.1.tar.gz
Writing /tmp/easy_install-KTBT99/DIRECT-1.0.1/setup.cfg
Running DIRECT-1.0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-KTBT99/DIRECT-1.0.1/egg-dist-tmp-TGidFl
Reading fortran codes...
	Reading file 'src/direct.pyf' (format:free)
Post-processing...
	Block: direct__user__routines
		Block: direct_user_interface
			Block: fcn
	Block: direct
			Block: direct
In: src/direct.pyf:direct:unknown_interface:direct
get_useparameters: no module direct__user__routines info used by direct
Post-processing (stage 2)...
Building modules...
	Constructing call-back function "cb_fcn_in_direct__user__routines"
	  def fcn(x,iidata,ddata,cdata,[n,iisize,idsize,icsize]): return f,flag
	Building module "direct"...
		Constructing wrapper function "direct"...
		  x,fmin,ierror = direct(fcn,eps,maxf,maxt,l,u,algmethod,logfilename,fglobal,fglper,volper,sigmaper,iidata,ddata,cdata,[n,iisize,idsize,icsize,fcn_extra_args])
		Constructing COMMON block support for "directcontrol"...
		  jones
	Wrote C/API module "direct" to file "build/src.linux-x86_64-2.7/src/directmodule.c"
	Fortran 77 wrappers are saved to "build/src.linux-x86_64-2.7/src/direct-f2pywrappers.f"
Could not locate executable gfortran
Could not locate executable f95
Could not locate executable ifort
Could not locate executable ifc
Could not locate executable lf95
Could not locate executable pgfortran
Could not locate executable f90
Could not locate executable f77
Could not locate executable fort
Could not locate executable efort
Could not locate executable efc
Could not locate executable g77
Could not locate executable g95
Could not locate executable pathf95
don't know how to compile Fortran code on platform 'posix'
warning: build_ext: f77_compiler=None is not available.

error: Setup script exited with error: extension 'DIRECT.direct' has Fortran sources but no Fortran compiler found`

**Comment by qqTYXn7** [comment]
Installed gfortran package and now it's giving the error:
`... a lot of stuff ...
Warning: Unused dummy argument ‘file’ at (1) [-Wunused-dummy-argument]
src/DIRsubrout.f:1222:30:

      +               l,u,file2,maxfunc,maxdeep,n,maxor,length)
                              1
Warning: Unused dummy argument ‘file2’ at (1) [-Wunused-dummy-argument]
src/DIRsubrout.f:1221:38:

       SUBROUTINE DIRWriteHistBox(point,f,thirds,c,anchor,actdeep,file,
                                      1
Warning: Unused dummy argument ‘point’ at (1) [-Wunused-dummy-argument]
src/DIRsubrout.f:1256:57:

      +               iidata, iisize, ddata, idsize, cdata, icsize)
                                                         1
Warning: Unused dummy argument ‘cdata’ at (1) [-Wunused-dummy-argument]
src/DIRsubrout.f:1256:42:

      +               iidata, iisize, ddata, idsize, cdata, icsize)
                                          1
Warning: Unused dummy argument ‘ddata’ at (1) [-Wunused-dummy-argument]
src/DIRsubrout.f:1256:27:

      +               iidata, iisize, ddata, idsize, cdata, icsize)
                           1
Warning: Unused dummy argument ‘iidata’ at (1) [-Wunused-dummy-argument]
src/DIRsubrout.f:1253:48:

      +               algmethod, maxfunc, maxdeep,    
                                                1
Warning: Unused dummy argument ‘maxdeep’ at (1) [-Wunused-dummy-argument]
src/DIRsubrout.f:1252:44:

       SUBROUTINE DIRheader(logfile,version,x,n,eps,maxf,maxT,l,u,
                                            1
Warning: Unused dummy argument ‘x’ at (1) [-Wunused-dummy-argument]
src/DIRsubrout.f:1414:45:

      +               fglobal, numfunc, Ierror)
                                             1
Warning: Unused dummy argument ‘ierror’ at (1) [-Wunused-dummy-argument]
src/DIRsubrout.f:155:0:

           S(maxpos,2) = novaluedeep
 ^
Warning: ‘novaluedeep’ may be used uninitialized in this function [-Wmaybe-uninitialized]
No eggs found in /tmp/easy_install-651M4j/DIRECT-1.0.1/egg-dist-tmp-rUeKs_ (setup script problem?)
error: The 'DIRECT' distribution was not found and is required by RoBO`

**Comment by qqTYXn7** [comment]
Ran dependencies script again and it seems to have worked now.
Haven't used it yet, just installed it.
Will update if there are any problems.
