### ISSUE TITLE
Benchmarks not updated in automl/HPOlib2

### ISSUE THREAD

**Issue by tinutjoy** [automl/RoBO#85]
Hi There,

The benchmark experiments used in RoBO are not updated in automl/HPOlib2 codebase (for e.g. hpolib.benchmarks.ml.residual_networks and SvmOnAdult, SvmOnHiggs, SvmOnLetter). Is there any other branch of HPOlib2  where I can get these benchmarks?

Thanks,

**Comment by aaronkl** [comment]
Hi,
they are on the development branch of HPOlib2
cheers
Aaron
