### ISSUE TITLE
Gradient of posterior mean and std of Gaussian Process

### ISSUE THREAD

**Issue by tobyclh** [automl/RoBO#90]
Hello, I am looking into the code and realize that while the acquisition function like expected improvement provides gradient information, Gaussian process itself doesn't have posterior gradient information provided.
is it possible to implement it like they do over [here](http://mlg.eng.cam.ac.uk/mchutchon/DifferentiatingGPs.pdf)

**Comment by aaronkl** [comment]
Hi, unfortunately the GP library george doesn't allow for gradient computation of the kernel. I've stared to switch to gpflow (tensor_flow branch) which provides gradient information such that it probably would be possible to implement this method.

**Comment by tobyclh** [comment]
Thanks for the response, that confirms my suspect. 
If you are trying to do it with ML package, I would also recommend Pyro from Uber, they have really solid code base, great pytorch autograd support and friendly people :beer:
