### ISSUE TITLE
Can't import "HyperBand_DataSubsetsOriginalIncumbent"

### ISSUE THREAD

**Issue by tinutjoy** [automl/RoBO#91]
Hi There,

I have searched for this particular file, "solver.hyperband_datasets_size_original_incumbent", in all the branches, but I was not able to find it. Can you please tell me where do you have the source file that implements hyperband?

Cheers,

**Comment by tinutjoy** [comment]
The demo for hyperband RoBO/experiments/fabolas/run_hyperband.py needs to be fixed.

Cheers,
Tinu

**Comment by aaronkl** [comment]
Note that we have a new distributed version of Hyperband https://github.com/automl/HpBandSter which can handle any kind of budget
