### ISSUE TITLE
george package path from requirement no longer exists

### ISSUE THREAD

**Issue by kejiashi** [automl/RoBO#93]
The george repository from @sfalkner no longer exists. Was this an edited version of the original george package? Now calling of GP related functions like "bayesian_optimization" seem to break...

I get the same error like #92 . Is this the reason?

**Comment by sfalkner** [comment]
We updated the requirement.txt file to point to the new repo where our george fork now lives. This should be fixed now, please reopen if you still encounter problems.

**Comment by kejiashi** [comment]
Solved. Thanks! You may also want to update for the development branch as well :)

**Comment by linxiaofan1234** [comment]
怎样解决的

**Comment by linxiaofan1234** [comment]
sorry,but how to  solve it,thanks

**Comment by linxiaofan1234** [comment]
@sfalkner ，thanks,I  thought I have solved,I  Restart the system,it works,thanks very much.
